In [ ]:
import numpy as np

### Write a NumPy program to generate five random numbers from the normal distribution.

Expected Output:
[-0.43262625 -1.10836787 1.80791413 0.69287463 -0.53742101]

In [ ]:
x = np.random.normal(size=5)
print(x)

[-1.46154957 -1.28401893  0.14272361 -2.16913399  1.07554672]


### Write a NumPy program to generate six random integers between 10 and 30.

Expected Output:
[20 28 27 17 28 29]

In [ ]:
x = np.random.randint(low=10, high=30, size=6)
print(x)

[29 10 10 28 23 15]


### Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

input: 

x = np.array([3, 5])

y = np.array([2, 5])

In [ ]:
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


### Write a NumPy program to create a 3x3 identity matrix.

In [ ]:
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Write a NumPy program to get the powers of an array values element-wise. 

Note: First array elements raised to powers from second array

Expected Output:

Original array
[0 1 2 3 4 5 6]

First array elements raised to powers from second array, element-wise:
[ 0 1 8 27 64 125 216]

In [ ]:
x = np.arange(7)
print("Original array")
print(x)
print("First array elements raised to powers from second array, element-wise:")
print(np.power(x, 3))

Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[  0   1   8  27  64 125 216]


### Write a NumPy program to repeat all the elements three times of a given array of string 

Expected Output:

Original Array:
['Python' 'PHP' 'Java' 'C++']

New array:
['PythonPythonPython' 'PHPPHPPHP' 'JavaJavaJava' 'C++C++C++']

In [ ]:
x1 = np.array(['Python', 'PHP', 'Java', 'C++'])
print("Original Array:")
print(x1)
new_array = np.char.multiply(x1, 3)
print("New array:")
print(new_array)

Original Array:
['Python' 'PHP' 'Java' 'C++']
New array:
['PythonPythonPython' 'PHPPHPPHP' 'JavaJavaJava' 'C++C++C++']


### Write a NumPy program to remove the leading whitespaces of all the elements of a given array. 

Sample Output:

Original Array:
[' python exercises ' ,' PHP ' ,' java ' ,' C++']

Remove the leading whitespaces : ['python exercises ', 'PHP ' ,'java ' ,'C++']

In [ ]:
x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'])
print("Original Array:")
print(x)
stripped = np.char.strip(x)
print("\nRemove the leading and trailing whitespaces: ", stripped)

Original Array:
[' python exercises ' ' PHP  ' ' java  ' '  C++']

Remove the leading and trailing whitespaces:  ['python exercises' 'PHP' 'java' 'C++']


### Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height. 

Sample Output:

Original array:

[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
(b'Pit', 5, 40.11)]

Sort by height

[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
(b'Nail', 6, 52.5 )]

In [ ]:
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
# create a structured array
students = np.array(students_details, dtype=data_type)   
print("Original array:")
print(students)
print("Sort by height")
print(np.sort(students, order='height')) 

Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
Sort by height
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


### Write a NumPy program to get the indices of the sorted elements of a given array. 

Expected Output:

Original array:

[1023 5202 6230 1671 1682 5241 4532]

Indices of the sorted elements of a given array:

[0 3 4 6 1 5 2]

In [ ]:
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
print("Original array:")
print(student_id)
i = np.argsort(student_id)
print("Indices of the sorted elements of a given array:")
print(i)

Original array:
[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]


### Write a NumPy program to sort an given array by the nth column.

Original array:

[[1 5 0]

[3 2 5]

[8 7 6]]

Sort the said array by the nth column:

[[3 2 5]

[1 5 0]

[8 7 6]]

In [ ]:
print("Original array:\n")
nums = np.random.randint(0,10,(3,3))
print(nums)
print("\nSort the said array by the nth column: ")
print(nums[nums[:,1].argsort()])

Original array:

[[8 9 5]
 [8 5 9]
 [9 8 1]]

Sort the said array by the nth column: 
[[8 5 9]
 [9 8 1]
 [8 9 5]]


### Write a NumPy program to get the dates of yesterday, today and tomorrow.

Sample Output:

Yestraday:  2022-04-11

Today:  2022-04-12

Tomorrow:  2022-04-13

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2022-04-13
Today:  2022-04-14
Tomorrow:  2022-04-15


### Write a NumPy program to find the number of weekdays in March 2017.
Note: "busday" default of Monday through Friday being valid days.

Sample Output:

Number of weekdays in March 2022:
23

In [ ]:
print("Number of weekdays in March 2022:")
print(np.busday_count('2022-03', '2022-04'))

Number of weekdays in March 2022:
23


### Write a NumPy program to convert numpy datetime64 to Timestamp.

Sample output:

Current date:
2022-04-12 12:28:12.526553

Timestamp:
1649766492.526553

UTC from Timestamp:
2022-04-12 12:28:12.526553

In [ ]:
from datetime import datetime
dt = datetime.utcnow()
print("Current date:")
print(dt)
dt64 = np.datetime64(dt)
ts = (dt64 - np.datetime64('1970-01-01T00:00:00Z')) / np.timedelta64(1, 's')
print("Timestamp:")
print(ts)
print("UTC from Timestamp:")
print(datetime.utcfromtimestamp(ts))

Current date:
2022-04-14 13:50:39.731599
Timestamp:
1649944239.731599
UTC from Timestamp:
2022-04-14 13:50:39.731599


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  


### Write a NumPy program to get true division of the element-wise array inputs.

Expected Output:

Original array:
[0 1 2 3 4 5 6 7 8 9]

Division of the array inputs, element-wise:
[ 0. 0.33333333 0.66666667 1. 1.33333333 1.6666666
7 2. 2.33333333 2.66666667 3. ]

In [ ]:
x = np.arange(10)
print("Original array:")
print(x)
print("Division of the array inputs, element-wise:")
print(np.true_divide(x, 3))

Original array:
[0 1 2 3 4 5 6 7 8 9]
Division of the array inputs, element-wise:
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


### Write a NumPy program to get the largest integer smaller or equal to the division of the inputs. 

Expected Output:

Original array:
[1.0, 2.0, 3.0, 4.0]

Largest integer smaller or equal to the division of the inputs:
[ 0. 1. 2. 2.]

In [ ]:
x = [1., 2., 3., 4.]
print("Original array:")
print(x)
print("Largest integer smaller or equal to the division of the inputs:")
print(np.floor_divide(x, 1.5))

Original array:
[1.0, 2.0, 3.0, 4.0]
Largest integer smaller or equal to the division of the inputs:
[0. 1. 2. 2.]


### Write a NumPy program to sort the specified number of elements from beginning of a given array. 

Sample output:

Original array:
[0.39536213 0.11779404 0.32612381 0.16327394 0.98837963 0.25510787 0.01398678 0.15188239 0.12057667 0.67278699]

Sorted first 5 elements:
[0.01398678 0.11779404 0.12057667 0.15188239 0.16327394 0.25510787 0.39536213 0.98837963 0.32612381 0.67278699]

In [ ]:
nums =  np.random.rand(10)
print("Original array:")
print(nums)
print("\nSorted first 5 elements:")
print(nums[np.argpartition(nums,range(5))])

Original array:
[0.21429403 0.34197934 0.672059   0.22829598 0.08831722 0.09769704
 0.49379181 0.5926089  0.76595179 0.72188262]

Sorted first 5 elements:
[0.08831722 0.09769704 0.21429403 0.22829598 0.34197934 0.672059
 0.49379181 0.5926089  0.76595179 0.72188262]
